// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaOrganizer.API.Contexts;

namespace NinjaOrganizer.API.Migrations
{
    [DbContext(typeof(NinjaOrganizerContext))]
    partial class NinjaOrganizerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NinjaOrganizer.API.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasMaxLength(200);

                    b.Property<DateTime>("Created");

                    b.Property<int>("Priority");

                    b.Property<int>("State");

                    b.Property<int>("TaskboardId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime?>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("TaskboardId");

                    b.ToTable("Cards");

                    b.HasData(
                        new { Id = 1, Content = "opis zadanie 1 tablicy 1", Created = new DateTime(2020, 5, 16, 13, 47, 19, 127, DateTimeKind.Local), Priority = 1, State = 1, TaskboardId = 1, Title = "zadanie 1 tablicy 1" },
                        new { Id = 2, Content = "opis zadanie 2 tablicy 1", Created = new DateTime(2020, 5, 16, 13, 47, 19, 129, DateTimeKind.Local), Priority = 1, State = 2, TaskboardId = 1, Title = "zadanie 2 tablicy 1" },
                        new { Id = 3, Content = "opis zadanie 1 tablicy 2", Created = new DateTime(2020, 5, 15, 13, 47, 19, 129, DateTimeKind.Local), Priority = 1, State = 1, TaskboardId = 2, Title = "zadanie 1 tablicy 2", Updated = new DateTime(2020, 5, 16, 13, 47, 19, 129, DateTimeKind.Local) },
                        new { Id = 4, Content = "opis zadanie 2 tablicy 2", Created = new DateTime(2020, 5, 16, 13, 47, 19, 129, DateTimeKind.Local), Priority = 3, State = 1, TaskboardId = 2, Title = "zadanie 2 tablicy 2" }
                    );
                });

            modelBuilder.Entity("NinjaOrganizer.API.Entities.Taskboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime?>("Updated");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Taskboards");

                    b.HasData(
                        new { Id = 1, Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Description = "opis tablicy pierwszej usera 1", Title = "Tablica 1 usera 1", UserId = 1 },
                        new { Id = 2, Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Description = "opis tablicy drugiej usera 1", Title = "Tablica 2 usera 1", UserId = 1 },
                        new { Id = 3, Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Description = "opis tablicy pierwszej usera 2", Title = "tablica 1 usera 2", UserId = 2 },
                        new { Id = 4, Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Description = "opis tablicy pierwszej usera 2", Title = "Tablica 2 usera 2", UserId = 2 }
                    );
                });

            modelBuilder.Entity("NinjaOrganizer.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, FirstName = "First name of user 1", LastName = "Last name os user 1", Username = "User 1" },
                        new { Id = 2, FirstName = "First name os user 2", LastName = "Last name of user 2", Username = "User 2" }
                    );
                });

            modelBuilder.Entity("NinjaOrganizer.API.Entities.Card", b =>
                {
                    b.HasOne("NinjaOrganizer.API.Entities.Taskboard", "Taskboard")
                        .WithMany("Cards")
                        .HasForeignKey("TaskboardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NinjaOrganizer.API.Entities.Taskboard", b =>
                {
                    b.HasOne("NinjaOrganizer.API.Entities.User", "User")
                        .WithMany("Taskboards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
